<form action="<?= $this->url(array("controller" => "usuario", "action" => "create"), null, true) ?>" method="post">
    <table width="100%" cellpadding="3" cellspacing="2">
        <tr>
            <td><input type="text" name="email" value="" placeholder="Email" /></td>
        </tr>
        <tr>
            <td><input type="text" name="nome" value="" placeholder="Nome" /></td>
        </tr>
        <tr>
            <td><input type="date" name="data_nasc" value="" placeholder="Data de Nascimento" /></td>
        </tr>
        <tr>
            <td><input type="password" name="senha" value="" placeholder="Senha" /></td>
        </tr>

    </table>
    <input type="submit" value="Cadastrar" />
</form>