
        <div class="row footer">
            <div class="container col12">
                <p class="tagline">Por um futuro em que as pessoas vivam em harmonia com a natureza.</p>

                <ul class="auxiliary-nav">

                    <li><a href="/privacidade/">Política de privacidade</a></li>

                    <li><a href="/contato/">Contato</a></li>

                    <li><a href="/intranet/">Acesso restrito</a></li>

                    <li><a href="/english/">English</a></li>

                    <li><a href="/rss.cfm">RSS/Web Feeds</a></li>
                </ul>

                <p class="meta">Photos and graphics &copy; WWF or used with permission. Text available under a <a href="http://creativecommons.org/licenses/by-sa/3.0/deed.pt" target="_blank">Creative Commons licence</a>.</p>
            </div>
        </div>
    </body>
</html>