

        <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery-1.12.3.min.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/bootstrap.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/npm.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/responsive.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')) ?>

        <?php echo $this->headScript() ?>
        </div>
    </body>
</html>