<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headTitle('Poltroneando') ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo $this->headMeta() ?>

        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/bootstrap.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/reset.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/global.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/global-responsive.css', 'screen') ?>

        <?php echo $this->headLink() ?>
    </head>
    <body class="body poltroneando">
        <div class="container-principal">
            <header>
                <div id="topo">
                    <nav class="direita">
                        <a class="mobile direita"><img src="/images/user-menu.png" alt=""></a>                        
                        <ul>
                            <li><?php
                                if ($this->usuario != null) {
                                    ?><a><?php
                                        echo $this->usuario->nome;
                                        ?>
                                        <span class="caret"></span></a>
                                    <ul class="submenu">
                                        <li>
                                            <a href="<?php
                                            echo $this->url(array('controller' => 'auth', 'action' => 'logout'), null, true);
                                            ?>">Logout</a>
                                        </li>
                                    </ul>
                                <?php } else {
                                    ?>
                                    <a href="<?php
                                    echo $this->url(array('controller' => 'auth'), null, true);
                                    ?>">Login</a>
                                       <?php
                                   }
                                   ?>
                            </li>
                            <!--<li><a>teste</a></li>-->
                        </ul>
                    </nav>
                    <nav class="">
                        <a class="mobile"><img src="/images/config-menu.png" alt=""></a> 

                    </nav>
                </div>
                <nav class="navbar navbar-default" id="nav1" role="navigation">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#elementoCollapse1" id="collap-button">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>                            
                            </button>
                            <div class="bck-img">
                                <a href="/" id="logo" ><img src="/images/logo2.jpg" width="48" height="47" class="img-circle" alt="Poltroneando" /></a>
                            </div>
                        </div>
                        <?php
                        if ($this->usuario == null) {
                            //    echo 0;
                        } else {
                            //    echo $this->usuario->email;
                        }
                        ?>
                        <div class="collapse navbar-collapse" id="elementoCollapse1">
                            <form class="navbar-form navbar-right" role="search" id="search">
                                <div class="form-group">
                                    <input title="Busca" value="" type="text" class="form-control" placeholder="Busca" id="s">
                                    <input type="submit" id="search-button" value="Ok"/> 
                                </div>
                            </form>

                        </div>
                    </div>
                </nav>
            </header>
