<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headTitle('Poltroneando') ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo $this->headMeta() ?>

        <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/bootstrap.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery-ui.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery-ui-1.10.2.custom.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/jquery.maskedinput.js') ?>
        <?php $this->headScript()->appendFile($this->baseURL() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')) ?>

        <?php echo $this->headScript() ?>

        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/jquery-ui.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/bootstrap.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/font-awesome.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/font-awesome-ie7.min.css', 'screen', 'IE 7') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/global.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/nav.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/global.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/bootstrap-responsive.css', 'screen') ?>

        <?php echo $this->headLink() ?>
    </head>
    <body>

        <div id="TB" class="aqua homepage">

            <div id="header">
                <div id="header-inner">
                    <a href="/" id="logo"><img src="/images/logo.jpg" width="104" height="104" alt="Poltroneando" /></a>
                    <form  action="/index.cfm" method="get" rel="nofollow" name="formsearch" id="search">

                        <input title="Busca" type="text" value="" name="uGlobalSearch" id="s" />

                        <input type="submit" id="search-button" value="Busca" />
                    </form>
                    <a id="open-menu" href="#nav">Menu</a>
                </div>
            </div>
        </div>