<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headTitle('Poltroneando') ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo $this->headMeta() ?>

        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/bootstrap.css', 'screen') ?>
        <?php $this->headLink()->appendStylesheet($this->baseURL() . '/css/global.css', 'screen') ?>

        <?php echo $this->headLink() ?>
    </head>
    <body class="body poltroneando">

        <!--<div id="TB" class="aqua homepage">-->
        <nav class="navbar navbar-default" id="nav1" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#elementoCollapse1" id="collap-button">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                            
                    </button>
                    <div class="bck-img">
                        <a href="/" id="logo" ><img src="/images/logo2.jpg" width="49" height="49" class="img-circle" alt="Poltroneando" /></a>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="elementoCollapse1">
                    <form class="navbar-form navbar-right" role="search" id="search">
                        <div class="form-group">
                            <input title="Busca" value="" type="text" class="form-control" placeholder="Busca" id="s">
                            <input type="submit" id="search-button" value="Ok"/> 
                        </div>
                    </form>
                </div>  
            </div>
        </nav>
        <!--            <div id="header">
                        <div id="header-inner">
                            <a href="/" id="logo"><img src="/images/logo.jpg" width="104" height="104" alt="Poltroneando" /></a>
                            <form  action="/index.cfm" method="get" rel="nofollow" name="formsearch" id="search">
        
                                <input title="Busca" type="text" value="" id="s" />
        
                                <input type="submit" id="search-button" value="Busca" />
                            </form>
                            <div id="nav">
                                <li class="home-link selected"><a href="/"></a></li>
                            </div>
                        </div>
                    </div>-->
        <!--</div>-->